export interface Concept {
  id: string;
  title: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  description: string;
  keyPoints: string[];
  example: string;
  formula?: string;
}

export const cmaInterManagementAccountingConcepts: Concept[] = [
  {
    id: 'cma-i-ma-1',
    title: 'Introduction to Management Accounting',
    difficulty: 'intermediate',
    description: 'Concepts, scope, and role of management accounting in business decision making.',
    keyPoints: [
      'Definition and scope of management accounting',
      'Difference from financial and cost accounting',
      'Functions of management accounting',
      'Tools and techniques',
      'Role in decision making and planning'
    ],
    example: 'Management accounting provides internal financial information to help managers make informed business decisions.',
  },
  {
    id: 'cma-i-ma-2',
    title: 'Activity Based Costing',
    difficulty: 'intermediate',
    description: 'ABC system for accurate cost allocation based on activities that drive costs.',
    keyPoints: [
      'Limitations of traditional costing',
      'ABC concepts and terminology',
      'Cost drivers and cost pools',
      'Implementation of ABC system',
      'Advantages and limitations'
    ],
    example: 'ABC allocates overhead costs to products based on activities consumed rather than using a single overhead rate.',
  },
  {
    id: 'cma-i-ma-3',
    title: 'Marginal Costing',
    difficulty: 'intermediate',
    description: 'Principles of marginal costing, CVP analysis, and contribution margin.',
    keyPoints: [
      'Marginal cost and contribution',
      'Fixed and variable costs',
      'Break-even analysis',
      'Profit-volume ratio',
      'Margin of safety'
    ],
    example: 'Contribution is the difference between sales and variable costs, which contributes to covering fixed costs and profit.',
    formula: 'Contribution = Sales - Variable Costs; P/V Ratio = (Contribution / Sales) × 100'
  },
  {
    id: 'cma-i-ma-4',
    title: 'Application of Marginal Costing in Short-Term Decision Making',
    difficulty: 'intermediate',
    description: 'Using marginal costing for make or buy, product mix, and other short-term decisions.',
    keyPoints: [
      'Make or buy decisions',
      'Product mix decisions',
      'Acceptance of special orders',
      'Shut down or continue decisions',
      'Sell or process further'
    ],
    example: 'In make or buy decisions, compare the marginal cost of making with the purchase price from outside.',
  },
  {
    id: 'cma-i-ma-5',
    title: 'Transfer Pricing',
    difficulty: 'intermediate',
    description: 'Methods and principles of transfer pricing between divisions within an organization.',
    keyPoints: [
      'Concept and objectives of transfer pricing',
      'Transfer pricing methods',
      'Market-based, cost-based, negotiated prices',
      'Impact on divisional performance',
      'International transfer pricing'
    ],
    example: 'Market-based transfer price uses the external market price for goods transferred between divisions.',
  },
  {
    id: 'cma-i-ma-6',
    title: 'Standard Costing and Variance Analysis',
    difficulty: 'intermediate',
    description: 'Setting standards, calculating variances, and analyzing deviations from standards.',
    keyPoints: [
      'Standard costing system',
      'Types of standards',
      'Material, labour, and overhead variances',
      'Sales variances',
      'Variance analysis and investigation'
    ],
    example: 'Material price variance measures the difference between actual price paid and standard price for actual quantity.',
    formula: 'Material Price Variance = (Standard Price - Actual Price) × Actual Quantity'
  },
  {
    id: 'cma-i-ma-7',
    title: 'Forecasting, Budgeting and Budgetary Control',
    difficulty: 'intermediate',
    description: 'Preparation of budgets, forecasting techniques, and budgetary control systems.',
    keyPoints: [
      'Forecasting techniques',
      'Types of budgets - master, flexible, zero-based',
      'Budget preparation process',
      'Budgetary control',
      'Performance evaluation using budgets'
    ],
    example: 'Flexible budget adjusts for changes in activity level, making it useful for performance evaluation.',
  },
  {
    id: 'cma-i-ma-8',
    title: 'Divisional Performance Measurement',
    difficulty: 'intermediate',
    description: 'Evaluation of divisional performance using ROI, RI, EVA, and other metrics.',
    keyPoints: [
      'Return on Investment (ROI)',
      'Residual Income (RI)',
      'Economic Value Added (EVA)',
      'Balanced scorecard',
      'Divisional profitability analysis'
    ],
    example: 'ROI measures the return generated by a division relative to its investment.',
    formula: 'ROI = (Divisional Profit / Divisional Investment) × 100'
  },
  {
    id: 'cma-i-ma-9',
    title: 'Responsibility Accounting',
    difficulty: 'intermediate',
    description: 'Responsibility centers, performance reporting, and controllable costs.',
    keyPoints: [
      'Concept of responsibility accounting',
      'Types of responsibility centers',
      'Cost, profit, investment, and revenue centers',
      'Controllable vs non-controllable costs',
      'Performance reporting'
    ],
    example: 'A profit center manager is responsible for both revenues and costs under their control.',
  },
  {
    id: 'cma-i-ma-10',
    title: 'Decision Theory',
    difficulty: 'intermediate',
    description: 'Decision making under uncertainty using probability, expected value, and decision trees.',
    keyPoints: [
      'Types of decision environments',
      'Expected value and expected opportunity loss',
      'Decision trees',
      'Value of perfect information',
      'Sensitivity analysis'
    ],
    example: 'Expected value is calculated by multiplying each outcome by its probability and summing the results.',
    formula: 'Expected Value = Σ (Probability × Outcome)'
  }
];
